CREATE TABLE `cot013` (
  `Loc_cod` smallint NOT NULL,
  `pre_nro` bigint NOT NULL,
  `pre_est` char(1) NOT NULL,
  `pre_gl1` char(40) NOT NULL,
  `pre_gl2` char(40) NOT NULL,
  `pre_gl3` char(40) NOT NULL,
  `pre_gl4` char(40) NOT NULL,
  `pre_gl5` char(40) NOT NULL,
  `pre_gl6` char(40) NOT NULL,
  `pre_fecAdj` date NOT NULL,
  `pre_fec` date NOT NULL,
  `sol_nro` bigint DEFAULT NULL,
  `pre_rut` int NOT NULL,
  `pre_suc` smallint NOT NULL,
  `pre_VenCod` smallint NOT NULL,
  `pre_req` char(20) NOT NULL,
  `pre_ate` char(20) NOT NULL,
  `pre_at1` char(20) NOT NULL,
  `pre_ent` char(15) NOT NULL,
  `pre_entdd` smallint NOT NULL,
  `pre_lug` char(20) NOT NULL,
  `ConPag_cod` smallint DEFAULT NULL,
  `pre_ob1` char(70) NOT NULL,
  `pre_ob2` char(70) NOT NULL,
  `pre_ob3` char(70) NOT NULL,
  `pre_ob4` char(70) NOT NULL,
  `pre_ob5` char(70) NOT NULL,
  `pre_ob6` char(70) NOT NULL,
  `pre_ob7` char(70) NOT NULL,
  `pre_ob8` char(70) NOT NULL,
  `pre_ob9` char(70) NOT NULL,
  `pre_o10` char(70) NOT NULL,
  `pre_o11` char(70) NOT NULL,
  `pre_o12` char(70) NOT NULL,
  `pre_o13` char(70) NOT NULL,
  `pre_o14` char(70) NOT NULL,
  `pre_o15` char(70) NOT NULL,
  `pre_o16` char(70) NOT NULL,
  `pre_o17` char(70) NOT NULL,
  `pre_o18` char(70) NOT NULL,
  `pre_o19` char(70) NOT NULL,
  `pre_o20` char(70) NOT NULL,
  `pre_pie` char(30) NOT NULL,
  `pre_tip` char(1) NOT NULL,
  `pre_tc` decimal(10,2) NOT NULL,
  `pre_moncd` smallint NOT NULL,
  `pre_ref` text NOT NULL,
  `pre_trnFec` date NOT NULL,
  `pre_trnhor` char(8) NOT NULL,
  `pre_trnusu` char(10) NOT NULL,
  `pre_gar` smallint NOT NULL,
  `Pre_vbLib` smallint NOT NULL,
  `Pre_VbLibUsu` char(10) NOT NULL,
  `Pre_VBLibDt` date NOT NULL,
  `Pre_VbLibTime` char(8) NOT NULL,
  `pre_vb` smallint NOT NULL,
  `pre_VbUsu` char(10) NOT NULL,
  `pre_VbFec` date NOT NULL,
  `pre_VbTime` char(8) NOT NULL,
  `pre_vbgg` smallint NOT NULL,
  `pre_vbggUsu` char(10) NOT NULL,
  `pre_vbggDt` date NOT NULL,
  `pre_vbggTime` char(8) NOT NULL,
  `Pre_vbggAvi` smallint NOT NULL,
  `Pre_MailEnv` smallint NOT NULL,
  `pre_ConId` smallint NOT NULL,
  `Pre_MailUsu` char(10) NOT NULL,
  `Pre_MailFec` date NOT NULL,
  `Pre_MailTime` char(8) NOT NULL,
  `Pre_MailSubjet` text NOT NULL,
  `Pre_MailPara` text NOT NULL,
  `Pre_Neto` bigint NOT NULL,
  PRIMARY KEY (`Loc_cod`,`pre_nro`),
  KEY `COT13G` (`pre_VenCod`),
  KEY `COT13C` (`pre_rut`,`pre_suc`),
  KEY `COT13E` (`ConPag_cod`),
  KEY `COT13B` (`Loc_cod`,`sol_nro`),
  KEY `COT13D` (`Loc_cod`,`pre_fec`,`pre_rut`,`pre_suc`,`pre_nro`),
  KEY `COT13H` (`Loc_cod`,`Pre_vbggAvi`,`pre_vbggDt`,`pre_vbggTime`),
  KEY `COT13J` (`pre_rut`,`pre_ConId`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1

CREATE TABLE `ctbm01` (
  `UserCd` char(10) NOT NULL,
  `UserDs` char(30) NOT NULL,
  `UserLlave` char(6) NOT NULL,
  `UserCta` smallint NOT NULL,
  `UserParam` smallint NOT NULL,
  `UserMaes` smallint NOT NULL,
  `UserMovi` smallint NOT NULL,
  `UserUti` smallint NOT NULL,
  `UserCon` smallint NOT NULL,
  `UserPerf` smallint NOT NULL,
  `UserFolDte` char(10) NOT NULL,
  `UserDte` smallint NOT NULL,
  `UserChPass` char(1) NOT NULL,
  `UserNameMail` char(50) NOT NULL,
  `UserMail` char(50) NOT NULL,
  PRIMARY KEY (`UserCd`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8

CREATE TABLE `clientea` (
  `Cli_Code` int NOT NULL,
  `Cli_Name` char(50) NOT NULL,
  `Cli_Digi` char(1) NOT NULL,
  `cli_gircod` mediumint DEFAULT NULL,
  `Cli_NameL` char(60) NOT NULL,
  `Ven_Cod` smallint DEFAULT NULL,
  `Cli_Sele` char(1) NOT NULL,
  `Cli_Obs` text NOT NULL,
  `Cli_Dcto` decimal(4,2) NOT NULL,
  `Cli_GirDs1` char(30) NOT NULL,
  `Cli_GirDs2` char(30) NOT NULL,
  `cli_blo` smallint NOT NULL,
  `Cli_PagCod` smallint NOT NULL,
  `Cli_Est` smallint NOT NULL,
  `Cli_Cred` bigint NOT NULL,
  `Cli_Abo` bigint NOT NULL,
  `Cli_Fe` smallint NOT NULL,
  `Cli_MailSII` char(50) NOT NULL,
  `Cli_ExpoNro` char(20) NOT NULL,
  PRIMARY KEY (`Cli_Code`),
  KEY `CLIENTEAB` (`cli_gircod`),
  KEY `CLIENTEAC` (`Ven_Cod`),
  KEY `CLIENTEAD` (`Cli_PagCod`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8

CREATE TABLE `adq004` (
  `Loc_cod` smallint NOT NULL,
  `ocp_nro` bigint NOT NULL,
  `ocp_tip` smallint NOT NULL,
  `ConPag_cod` smallint NOT NULL,
  `ocp_ProCt` smallint NOT NULL,
  `ocp_ila` int NOT NULL,
  `ocp_pdt_obs` char(120) NOT NULL,
  `ocp_trnFec` date NOT NULL,
  `ocp_trnHor` char(8) NOT NULL,
  `ocp_trnusu` char(10) NOT NULL,
  `ocp_A1_Usu` char(10) NOT NULL,
  `ocp_A1_Dt` date NOT NULL,
  `ocp_A1_Hr` char(8) NOT NULL,
  `ocp_A1_Ap` smallint NOT NULL,
  `ocp_A2_Usu` char(10) NOT NULL,
  `ocp_A2_Dt` date NOT NULL,
  `ocp_A2_Hr` char(8) NOT NULL,
  `ocp_A2_Ap` smallint NOT NULL,
  `ocp_A3_Anu` smallint NOT NULL,
  `ocp_A3_Dt` date NOT NULL,
  `ocp_A3_Hr` char(8) NOT NULL,
  `ocp_A3_Usu` char(10) NOT NULL,
  `ocp_fec` date NOT NULL,
  `ocp_fee` date NOT NULL,
  `pro_rut` int NOT NULL,
  `pro_suc` smallint NOT NULL,
  `ocp_ate` char(25) NOT NULL,
  `ocp_ple` char(15) NOT NULL,
  `ocp_ob1` char(55) NOT NULL,
  `ocp_ob2` char(55) NOT NULL,
  `ocp_ob3` char(55) NOT NULL,
  `ocp_mpe` char(1) NOT NULL,
  `ocp_net` bigint NOT NULL,
  `ocp_iva` bigint NOT NULL,
  `ocp_pdt` char(1) NOT NULL,
  `ocp_A4_Ap` smallint NOT NULL,
  `ocp_A4_Dt` date NOT NULL,
  `ocp_A4_Hr` char(8) NOT NULL,
  `ocp_A4_Usu` char(10) NOT NULL,
  `ocp_moncd` smallint NOT NULL,
  `ocp_Tc` decimal(9,2) NOT NULL,
  PRIMARY KEY (`Loc_cod`,`ocp_nro`),
  KEY `ADQ04H` (`pro_rut`,`ocp_ProCt`),
  KEY `ADQ04B` (`pro_rut`,`pro_suc`),
  KEY `ADQ04D` (`ConPag_cod`),
  KEY `ADQ04F` (`Loc_cod`,`ocp_fec`),
  KEY `ADQ04G` (`ocp_fec`,`Loc_cod`),
  KEY `ADQ04E` (`ocp_moncd`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8

CREATE TABLE `proveea` (
  `pro_rut` int NOT NULL,
  `pro_nom` char(40) NOT NULL,
  `pro_mail` char(100) NOT NULL,
  `pro_cas` char(15) NOT NULL,
  `pro_fon` char(10) NOT NULL,
  `pro_fax` char(10) NOT NULL,
  `Pro_Est` smallint NOT NULL,
  `Pro_GirCod` mediumint NOT NULL,
  `Pro_PagCod` smallint DEFAULT NULL,
  `Pro_pagCred` bigint NOT NULL,
  PRIMARY KEY (`pro_rut`),
  KEY `PROVEEA02` (`Pro_GirCod`),
  KEY `PROVEEA03` (`Pro_PagCod`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8

